// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // O `datasource` deste prisma7.config.ts não suporta `directUrl` nesta
    // versão (7.10.0) — só `url`. Por isso usamos o "Session pooler" do
    // Supabase (porta 5432 no host do pooler): ele aceita prepared
    // statements, então serve tanto para a aplicação quanto para o CLI
    // rodar migrations. Veja o comentário no .env.example.
    url: process.env["DATABASE_URL"],
  },
});
